.TH MYSTRLEN 3 "2025-09-23" "libmputils" "Library Functions"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.nf
.B #include <mystrfunctions.h>
.sp
.BI "int mystrlen(const char *" s );
.fi
.SH DESCRIPTION
.B mystrlen()
calculates the length of the string
.I s
excluding the terminating null byte.
.SH AUTHOR
Ayesha Waheed <bsdsf23a010@pucit.edu.pk>
